### ISSUE TITLE
Config instructions?

### ISSUE THREAD

**Issue by j-greig** [sjelfull/craft3-autologin#2]
Could you provide some more instructions on configuring this plugin?

I'm not sure how to map usernames/url keys etc

Cheers!

**Comment by sjelfull** [comment]
Hmm, could you list the things you find unclear, and I will try to make them clearer?

I know it isn't 100% straightforward, but I still think the config file is pretty clear.

**Comment by colorao** [comment]
Hi.
I also have several doubts about config.

First of all, let me explain my scenario :
On a **LOCAL NETWORK** installation, I've got an index.html with several links to different CP sections (hosted in other servers) .
What I do need is the client to access to Control Panel with no login at all. 

On my local network,  I'm working on PC A (IP aaa.aaa.aaa.aaa). Then I open my browser and navigate to index.html hosted at a server B ( IP bbb.bbb.bbb.bbb). 
When I click on a link, I'd like to access directly to the Craft CP entries edition page hosted at server C (IP ccc.ccc.ccc.ccc) and logged-in as editor .

So there are 3 IP's involved :
A = my local PC's IP
B = The index.html server IP (referer)
C = Craft's CP server IP

And in Craft's CP I've got 2 different users:
name: admin & pass: adminPass
name: editor & pass: editorPass


OK. That's my scenario.
Now. I've installed autologin plugin, but I don't understand the instructions and  cannot make it work :


**ipWhitelist**
> // A list of Craft usernames/emails mapped to IPs
>     'ipWhitelist'       => [
>         'editor' => [
>             'WHAT_IP_SHOULD_BE_HERE',
>         ],
>     ],

What IP should I provide to be logged as editor? MY PC's IP aaa.aaa.aaa.aaa? or the referer IP I came from bbb.bbb.bbb.bbb ?
As I understand, If I click on an index.html link (http://ccc.ccc.ccc.ccc/web/admin/entries/slug), then I should be logged in as editor and access directly to CP ?
It does not work for me.

**basicAuth**
>     // A list of Craft usernames/emails mapped to basic auth usernames
>     'basicAuth'         => [
>         'editor' => 'basicAuthUsernameEditor',
>         'admin' => 'basicAuthUsernameAdmin',    
>     ],
I don't understand what basicAuth means and how should I use this kind of authentication.
What 'basicAuthUsernameEditor' should be set ?
How do I access Control Panel from outside and give those credentials to Craft ?

**urlKeys**
>     // A list of Craft usernames/emails mapped to url keys
>     'urlKeys'           => [
>         'editor' => 'InVeNtEdCuStOmKeYfOrEdItOr',
>         'admin' => 'InVeNtEdCuStOmKeYfOrAdMiN',
>     ],

Later,  you add:

> You can provide your users with a url that automatically logs them in. To set this up, you need a pair of username => password in the urlKeys setting.

What I must set is the user name and an invented password (key) for each user. Then later, add that key to an url. right?
So, the key is an invented key. Not the real password. right?

And last:

> After setting that up, you can login by going to siteurl.tld/autologin?key=BepmD8GQBZpaFpXQ
What URL is siteurl.tld ? I've got no siteurl, just CP's URL, because I'm using Craft as a JSON provider, with no front-end url.

I've tried all of this with no luck at all.
http://ccc.ccc.ccc.ccc/siteurl.tld/autologin?key=InVeNtEdCuStOmKeYfOrEdItOr
http://ccc.ccc.ccc.ccc/web/siteurl.tld/autologin?key=InVeNtEdCuStOmKeYfOrEdItOr
http://ccc.ccc.ccc.ccc/web/autologin?key=InVeNtEdCuStOmKeYfOrEdItOr
http://ccc.ccc.ccc.ccc/web/admin/autologin?key=InVeNtEdCuStOmKeYfOrEdItOr

Please, could you help me and explain where am I wrong?
Thanks in advanced.

**Comment by sjelfull** [comment]
```   
'ipWhitelist'       => [
        'editor' => [
            '162.247.141.58',
            '162.247.141.59',
        ],
    ],
```

If someone with IP address 162.247.141.58 accesses Craft, it will log them automatically in as the user with username `editor`.

```
    'basicAuth'         => [
        'editor' => 'fred',
    ],
```

If you have setup [basic authentication](https://swagger.io/docs/specification/authentication/basic-authentication/), and someone authenticates with the username `fred`, it will log them in as the user `editor` in Craft.

*urlKeys*

Correct, its a made-up key, not the user's password.

```
    // A list of Craft usernames/emails mapped to url keys
    'urlKeys'           => [
        'editor' => 'BepmD8GQBZpaFpXQ',
    ],
```

If you then access the site url `/autologin?key=BepmD8GQBZpaFpXQ` it will log you in as the user `editor`.

**Comment by colorao** [comment]
Hi Fred.
Thanks for your ultra-fast response.

> ```
> 'ipWhitelist'       => [
>         'editor' => [
>             '162.247.141.58',
>             '162.247.141.59',
>         ],
>     ],
> ```
> If someone with IP address 162.247.141.58 accesses Craft, it will log them automatically in as the user with username `editor`.

But that IP is the referer IP ? or my PC's own IP ?

> 
> ```
>     'basicAuth'         => [
>         'editor' => 'fred',
>     ],
> ```
> If you have setup [basic authentication](https://swagger.io/docs/specification/authentication/basic-authentication/), and someone authenticates with the username `fred`, it will log them in as the user `editor` in Craft.

Ok. I'll look into it.

> 
> _urlKeys_
> 
> Correct, its a made-up key, not the user's password.
> 
> ```
>     // A list of Craft usernames/emails mapped to url keys
>     'urlKeys'           => [
>         'editor' => 'BepmD8GQBZpaFpXQ',
>     ],
> ```
> If you then access the site url `/autologin?key=BepmD8GQBZpaFpXQ` it will log you in as the user `editor`.

I have installed Craft at 'craft' folder in my Apache (192.168.1.58) .
http://192.168.1.58/craft/autologin?key=BepmD8GQBZpaFpXQ  ==> 404
http://192.168.1.58/craft/web/autologin?key=BepmD8GQBZpaFpXQ  ==> Template not found:  autologin
http://192.168.1.58/craft/web/admin/autologin?key=BepmD8GQBZpaFpXQ  ==> redirection to login

Any clue?
Thanks again

**Comment by nfq** [comment]
Yeah, same of me. If https://foo.locacl/autologin?key=somekeyhere&cp=true, it doesn't redirect me to the CP but base url.

**Comment by nfq** [comment]
And yes, this is confusing to me `'editor' => 'fred',`. Isn't user and username the same thing in craft? How to differentiate here?

**Comment by engram-design** [comment]
Going to close this in favour of https://github.com/verbb/autologin/issues/10
